name: Syncfusion License

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: git checkout
      uses: actions/checkout@v4
    - name: pnpm setup
      uses: pnpm/action-setup@v3
      with:
        version: '9.1.0'
    - name: Install node modules
      run: pnpm install
    - name: Activate Syncfusion License
      run: npx syncfusion-license activate
      env:
        SYNCFUSION_LICENSE: ${{ secrets.SYNCFUSION_LICENSE }}
    - name: Deploy to Vercel
      env:
        VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
        VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}
      run: vercel --prod --token $VERCEL_TOKEN --projectId $VERCEL_PROJECT_ID