name: Syncfusion License

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: git checkout
      uses: actions/checkout@v3
    - name: pnpm setup
      uses: pnpm/action-setup@v2
    - name: Install node modules
      run: pnpm install
    - name: Activate Syncfusion License
      run: npx syncfusion-license activate
      env:
        SYNCFUSION_LICENSE: ${{ secrets.SYNCFUSION_LICENSE }}